apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
  annotations:
    # ALB annotations for AWS ALB Ingress Controller
    alb.ingress.kubernetes.io/scheme: internet-facing  # ALB Scheme (internet-facing or internal)
    alb.ingress.kubernetes.io/target-type: ip         # Using IP mode (instead of instance mode)
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /cart
            pathType: Prefix
            backend:
              service:
                name: retail-store-sample-cart-chart-carts
                port:
                  number: 80
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: retail-store-sample-catalog-chart
                port:
                  number: 80
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: retail-store-sample-orders-chart
                port:
                  number: 80
          - path: /checkout
            pathType: Prefix
            backend:
              service:
                name: retail-store-sample-checkout-chart
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retail-store-sample-ui-chart
                port:
                  number: 80
