{{- range $i, $ns := .Values.namespaces }}
{{- range $j, $sa := ($ns.serviceAccounts | default list) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $ns.name }}
  labels:
    {{- include "platform.labels" $ | nindent 4 }}
  annotations:
    {{- range $k, $v := ($sa.annotations | default dict) }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken | default false }}
---
{{- end }}
{{- end }}
